[package]
name = "hyper-trust-dns"
version = "0.5.0"
edition = "2021"
description = "HTTP/HTTPS connectors for hyper that use trust-dns' DNS resolver"
license = "MIT"
documentation = "https://docs.rs/hyper-trust-dns"
homepage = "https://github.com/Gelbpunkt/hyper-trust-dns"
repository = "https://github.com/Gelbpunkt/hyper-trust-dns"

[dependencies]
hyper = { version = "0.14", default-features = false, features = ["client", "runtime", "tcp"] }
trust-dns-resolver = { version = "0.23.0-alpha.2", default-features = false }

# Rustls
hyper-rustls = { version = "0.24", default-features = false, optional = true }

# Native-TLS
hyper-tls = { version = "0.5", default-features = false, optional = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["async_tokio"] }
hyper = { version = "0.14", default-features = false, features = ["client", "tcp", "http1", "http2"] }
hyper-rustls = { version = "0.24", default-features = false, features = ["tokio-runtime", "webpki-tokio", "http1", "http2"] }
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }

[features]
default = ["https-only", "rustls-webpki", "rustls-http1", "tokio"]
https-only = []

# Tokio feature
tokio = ["trust-dns-resolver/tokio-runtime", "hyper-rustls?/tokio-runtime"]

# Configuration features
system-config = ["trust-dns-resolver/system-config"]

# DNS features
dns-over-openssl = ["trust-dns-resolver/dns-over-openssl"]
dns-over-native-tls = ["trust-dns-resolver/dns-over-native-tls"]
dns-over-rustls = ["trust-dns-resolver/dns-over-rustls"]

dns-over-https-rustls = ["trust-dns-resolver/dns-over-https-rustls"]

dnssec-openssl = ["trust-dns-resolver/dnssec-openssl"]
dnssec-ring = ["trust-dns-resolver/dnssec-ring"]

# RustlsHttpsConnector options
rustls-webpki = ["hyper-rustls", "hyper-rustls/webpki-tokio"]
rustls-native = ["hyper-rustls", "hyper-rustls/native-tokio"]
rustls-http1 = ["hyper-rustls/http1"]
rustls-http2 = ["hyper-rustls/http2"]
rustls-tls-12 = ["hyper-rustls/tls12"]

# NativeTlsHttpsConnector options
native-tls = ["hyper-tls"]

[[bench]]
name = "requests_per_sec"
harness = false
path = "benches/requests_per_sec.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
