[package]
name = "hyper-trust-dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", default-features = false, features = ["client", "runtime", "tcp"] }
log = "0.4"
tokio = { version = "1", default-features = false, features = ["rt"] }
trust-dns-resolver = { version = "0.20", default-features = false, features = ["system-config", "tokio-runtime"] }

# Rustls
ct-logs = { version = "0.8", optional = true }
rustls = { version = "0.19", optional = true }
rustls-native-certs = { version = "0.5", optional = true }
tokio-rustls = { version = "0.22", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.21", optional = true }

# Native-TLS
bytes = { version = "1", optional = true }
native-tls-crate = { package = "native-tls", version = "0.2", optional = true }
tokio-native-tls = { version = "0.3", optional = true }

[dev-dependencies]
hyper = { version = "0.14", default-features = false, features = ["client", "tcp", "http1"] }
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }

[features]
default = ["rustls-webpki", "http1"]
http1 = ["hyper/http1"]
http2 = ["hyper/http2"]

# DNS features
__dns-over-tls = []
__dns-over-https = []
dns-over-openssl = ["trust-dns-resolver/dns-over-openssl", "__dns-over-tls"]
dns-over-native-tls = ["trust-dns-resolver/dns-over-native-tls", "__dns-over-tls"]
dns-over-rustls = ["trust-dns-resolver/dns-over-rustls", "__dns-over-tls"]
dns-over-https-rustls = ["trust-dns-resolver/dns-over-https-rustls", "__dns-over-https"]
dnssec-openssl = ["trust-dns-resolver/dnssec-openssl"]
dnssec-ring = ["trust-dns-resolver/dnssec-ring"]

# RustlsHttpsConnector options
__rustls = ["rustls", "tokio-rustls", "ct-logs"]
rustls-webpki = ["__rustls", "webpki", "webpki-roots"]
rustls-native = ["__rustls", "rustls-native-certs"]

# NativeTlsHttpsConnector options
native-tls = ["bytes", "native-tls-crate", "tokio-native-tls"]
